"""
backend/app/analysis/sandbox.py

Restricted Python code execution for the hybrid analysis layer.
Runs LLM-generated pandas code with only safe builtins and pre-injected
DataFrames from prior SQL steps.
"""

from __future__ import annotations

import json
import logging
import threading
from io import StringIO
from typing import Any

logger = logging.getLogger(__name__)

_SAFE_BUILTINS = {
    "len": len,
    "range": range,
    "round": round,
    "min": min,
    "max": max,
    "sum": sum,
    "sorted": sorted,
    "enumerate": enumerate,
    "zip": zip,
    "dict": dict,
    "list": list,
    "tuple": tuple,
    "set": set,
    "int": int,
    "float": float,
    "str": str,
    "bool": bool,
    "abs": abs,
    "print": print,
    "isinstance": isinstance,
    "True": True,
    "False": False,
    "None": None,
}

MAX_INPUT_ROWS = 10_000
TIMEOUT_SECONDS = 30


class _Timeout(Exception):
    pass


def run_code(
    code: str,
    step_data: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    """
    Execute *code* in a restricted namespace.

    Parameters
    ----------
    code : str
        Python source generated by the LLM. Must assign to a ``result``
        variable — either a dict with ``columns``+``rows`` keys or a
        summary string.
    step_data : dict
        Mapping of step_id -> {"columns": [...], "rows": [...]} from
        prior SQL steps. Each is injected as a pandas DataFrame named
        ``step_{step_id}``.

    Returns
    -------
    dict  {"ok": True, "columns": [...], "rows": [...], "summary": ...}
      or  {"ok": False, "error": "..."}
    """
    try:
        import pandas as pd
    except ImportError:
        return {"ok": False, "error": "pandas is not installed"}

    import math

    # Build namespace with DataFrames from prior steps
    namespace: dict[str, Any] = {
        "__builtins__": _SAFE_BUILTINS,
        "pd": pd,
        "json": json,
        "math": math,
    }

    for sid, data in step_data.items():
        cols = data.get("columns", [])
        rows = data.get("rows", [])[:MAX_INPUT_ROWS]
        df = pd.DataFrame(rows, columns=cols) if cols else pd.DataFrame()
        namespace[f"step_{sid}"] = df

    # Capture print output
    output_buf = StringIO()
    namespace["print"] = lambda *a, **kw: print(*a, file=output_buf, **kw)

    # Run with timeout
    exc_holder: list[Exception] = []

    def _target():
        try:
            exec(code, namespace)  # noqa: S102
        except Exception as e:
            exc_holder.append(e)

    thread = threading.Thread(target=_target, daemon=True)
    thread.start()
    thread.join(timeout=TIMEOUT_SECONDS)

    if thread.is_alive():
        return {"ok": False, "error": f"Code execution timed out after {TIMEOUT_SECONDS}s"}

    if exc_holder:
        return {"ok": False, "error": str(exc_holder[0])}

    # Extract result
    result = namespace.get("result")
    if result is None:
        printed = output_buf.getvalue().strip()
        if printed:
            return {"ok": True, "summary": printed}
        return {"ok": False, "error": "Code did not assign a `result` variable"}

    if isinstance(result, str):
        return {"ok": True, "summary": result}

    if isinstance(result, pd.DataFrame):
        cols = list(result.columns)
        rows = result.head(200).values.tolist()
        return {"ok": True, "columns": cols, "rows": rows}

    if isinstance(result, dict):
        return {"ok": True, **result}

    return {"ok": True, "summary": str(result)}
